*** Variables ***
${EN_ChequeType}                  xpath=//div[@id='chequeTypeCode']/div/div/div[1]
${EN_ChequeCancellationReason}    xpath=//div[@id='chequeCancelReasonCode']/div/div/div[1]
${EN_PayableAmount}               xpath=//input[@id='payableAmount']
${EN_RequestDate}                  xpath=//span[@id='requestDate']/div/input
${EN_TransactionStatusAfterOpus}        xpath=//div[@id='decision']/div/div/div[1]
