*** Variables ***
${EN_VP_CurrentPayoutOtion}     xpath=//input[@id='originalPayoutOption']
${EN_VP_PayoutOption}           xpath=//input[@id='payoutOptionDesc']
${EN_VP_NationalID}             xpath=//input[@id='promptpayId']
${EN_VP_CompletionDate}         xpath=//input[@id='endTime']
${EN_VP_Bank_Name}              xpath=//input[@id='bankName']
${EN_VP_Account_No}             xpath=//input[@id='accountNumber']
${EN_OWBbankName}               xpath=//input[@id='bankName']
